language: python
python:
  - 2.7.15
  - 3.6
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
  - PLONE_VERSION=5.1.x
matrix:
  exclude:
    - python: 3.6
      env: PLONE_VERSION=4.3.x
    - python: 3.6
      env: PLONE_VERSION=5.0.x
    - python: 3.6
      env: PLONE_VERSION=5.1.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/test-coverage
after_success:
  - pip install -q coveralls
  - coveralls
